### ISSUE TITLE
After migrate all docs transactions are empty

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/commercionetwork#77]
## Summary of Bug

Using the migrate command      

`cnd migrate v1.3.1 export_genesis_testnet4000.json --chain-id commercio-testnet5000 --genesis-time=2019-11-15T07:30:00Z > genesis_5000.json`

all docs transactions are disappeared 

## Version

1.3.1-16-g52f46ea     
commit hash: 4973c259c63a7bf9abaf5840110d74a843a11dc8

## Steps to Reproduce

1. `git clone https://github.com/commercionetwork/commercionetwork.git`
1. `cd commercionetwork`
1. `git checkout master`
1. `make build-linux` or build as your node architecture required
1. `cnd version` should be 1.3.1-16-g52f46ea
1. Transfer binaries in a working and syncronized full node of commercio-testnet4000. Example `scp -r ./build/Linux-AMD64 your_node_user@your_node_ip:.`. If your node is your machine you don't need transfer binaries
1. Access to node
1. Stop `cnd` deamon
1. `./Linux-AMD64/cnd export --for-zero-height --height=210000 > export_genesis.json`. Path depend on where you have your the binaries.
1. Restart `cnd` deamon if you need
1. `./Linux-AMD64/cnd migrate v1.3.1 export_genesis.json --chain-id commercio-testnet5000 --genesis-time=2019-11-15T07:30:00Z > genesis_5000.json`
1. **Optional** `sudo apt install jq` or install `jq with your package manager for your node
1. **Optional** `cat genesis_5000.json | jq "." > genesis_5000_formatted.json`
1. In the genesis file resulted by migration all docs are empty
```json
    "docs": {
      "documents": [], 
      "receipts": null, 
      "supported_metadata_schemes": [], 
      "trusted_metadata_schema_proposers": null
    }, 
```

[Archivio.zip](https://github.com/commercionetwork/commercionetwork/files/3850348/Archivio.zip)

**Comment by RiccardoM** [comment]
This problem is due to the fact that when migrating, we should specify the **target** version, not the source one. 

Thus being said, the next version will be `v1.3.2` and not `v1.3.1` again. So, the command should be: 

```
cnd migrate v1.3.2 export_genesis_testnet4000.json --chain-id commercio-testnet5000 --genesis-time=2019-11-15T07:30:00Z > genesis_5000.json
```

(Please note that I've replace `v1.3.1` with `v1.3.2`). 

To solve this problems in the future, inside 1c5d1d0f8905df51c54040e57a6a9b6f6d861ac9 I've added a new `cnd migrations-list` command and improved the documentation of the `cnd migrate` command. You can see the documentation of both using the `-h` flag: 

* `cnd migrations-list -h` 
* `cnd migrate -h` 

I've also added the `v1.3.2` migration, so the following command written above should now work properly. 

Please let me know if this fixes your problem. If so, we can close this issue.

**Comment by bragaz** [comment]
@marcotradenet can we close this one?
